/* Servidor local de administração. Nunca publique este processo. */
const http = require("http");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const ROOT = __dirname;
const MIME = { ".html": "text/html; charset=utf-8", ".js": "application/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".mp4": "video/mp4" };
function loadData(file) { const ctx = {}; vm.createContext(ctx); vm.runInContext(fs.readFileSync(file, "utf8") + ";globalThis.result={event:EVENT,gallery:GALLERY}", ctx); return ctx.result; }
function saveData(file, data) { fs.writeFileSync(file, "const EVENT = " + JSON.stringify(data.event, null, 2) + ";\n\nconst GALLERY = " + JSON.stringify(data.gallery, null, 2) + ";\n"); }
function removePhoto(relative) { if (!/^Semana da Família \d{4}\/.+\.(jpe?g|png)$/i.test(relative)) throw new Error("Caminho de imagem não permitido."); const target = path.resolve(ROOT, relative); if (!target.startsWith(ROOT + path.sep) || !fs.existsSync(target)) throw new Error("Fotografia não encontrada."); const folder = path.dirname(target); const dataFile = path.join(folder, "data.js"); const data = loadData(dataFile); if (!data.gallery.some(photo => photo.f === relative)) throw new Error("Fotografia não cadastrada no álbum."); fs.unlinkSync(target); data.gallery = data.gallery.filter(photo => photo.f !== relative); data.event.photoCount = data.gallery.length; saveData(dataFile, data); const eventsFile = path.join(ROOT, "events.js"); const ctx = {}; vm.createContext(ctx); vm.runInContext(fs.readFileSync(eventsFile, "utf8") + ";globalThis.items=EVENTS", ctx); ctx.items.forEach(item => { if (item.id === data.event.id) item.photoCount = data.gallery.length; }); fs.writeFileSync(eventsFile, "const EVENTS = " + JSON.stringify(ctx.items, null, 2) + ";\n"); return data.gallery.length; }
const server = http.createServer((req,res) => { const url = new URL(req.url, "http://127.0.0.1"); if (req.method === "DELETE" && url.pathname === "/api/photos") { try { const count = removePhoto(url.searchParams.get("path") || ""); res.writeHead(200,{"Content-Type":"application/json"}); res.end(JSON.stringify({ok:true,photoCount:count})); } catch (error) { res.writeHead(400,{"Content-Type":"application/json"}); res.end(JSON.stringify({ok:false,error:error.message})); } return; } const requested = decodeURIComponent(url.pathname === "/" ? "/index.html" : url.pathname); const file = path.resolve(ROOT, "." + requested); if (!file.startsWith(ROOT + path.sep) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) { res.writeHead(404); res.end("Not found"); return; } res.writeHead(200,{"Content-Type":MIME[path.extname(file).toLowerCase()]||"application/octet-stream"}); fs.createReadStream(file).pipe(res); });
const PORT = Number(process.env.PORT || 8000);
server.listen(PORT, "127.0.0.1", () => console.log("Administração local: http://127.0.0.1:" + PORT));
